#!/bin/sh

# Gradle start up script for POSIX generated by Gradle.
# This deliberately downloads only the Gradle distribution; Android SDK/NDK
# assets are managed separately by the Android build environment.

APP_HOME=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
elif command -v java >/dev/null 2>&1; then
    JAVACMD="java"
else
    echo "ERROR: JAVA_HOME is not set and no java command could be found." >&2
    exit 1
fi

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
    echo "ERROR: gradle-wrapper.jar is missing." >&2
    echo "Use Android Studio or run: gradle wrapper --gradle-version 8.2" >&2
    exit 1
fi

exec "$JAVACMD" ${GRADLE_OPTS:-} -Dorg.gradle.appname=gradlew \
    -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
